# Generated by Django 5.0 on 2024-04-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("capacidad", models.IntegerField()),
                ("disponible", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("AUD", "Auditorio"),
                            ("CON", "Sala de Conferencias"),
                            ("AUL", "Aula"),
                            ("LAB", "Laboratorio"),
                        ],
                        default="AUL",
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
