# Generated by Django 5.0 on 2024-04-23 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="sala",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas",
                to="bookings.sala",
            ),
        ),
    ]
